version: '3.4'

services:
  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    container_name: nexus
    user: "200:200"  # Specify the user and group IDs for the Nexus process
    volumes:
      - ./nexus-data:/nexus-data
    command: ["sh", "-c", "chown -R 200:200 /nexus-data && exec /opt/sonatype/nexus/bin/nexus run"]
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:9091/eureka/
      - keycloak-client.server-url=http://172.28.93.16:18080/auth # use host name or ip of the host machine
    depends_on:
      - eureka-server
      - nexus
  eureka-server:
    build:
      context: ./eureka-server
    ports:
      - "9091:9091"
    restart: on-failure
  keycloak:
    image: jboss/keycloak:11.0.0
    container_name: keycloak-server
    volumes:
      - ./keycloak-server/realm-export.json:/tmp/keycloak/config/realm-export.json
    environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        KEYCLOAK_IMPORT: /tmp/keycloak/config/realm-export.json
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
    ports:
      - "18080:18080"
    command:
      - "-b"
      - "0.0.0.0"
      - "-Djboss.socket.binding.port-offset=10000"
    restart: on-failure
    depends_on:
      - postgres
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      ports:
        - "5432:5432"
  microservice-candidat:
    build:
      context: ./microservice-candidat
    ports:
      - "9082:9082"
    restart: on-failure
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:9091/eureka/
      - keycloak-client.server-url=http://172.28.93.16:18080/auth
    depends_on:
      - eureka-server
      - nexus
  microservice-reservation:
    build: 
      context: ./microservice-reservation
    ports:
      - "9083:9083"
    restart: on-failure
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:9091/eureka/
      - keycloak-client.server-url=http://172.28.93.16:18080/auth 
    depends_on:
      - eureka-server
      - nexus
  microservice-review:
    build: 
      context: ./microservice-review
    ports:
      - "9084:9084"
    restart: on-failure
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:9091/eureka/
      - keycloak-client.server-url=http://172.28.93.16:18080/auth
      - spring.datasource.url=jdbc:mysql://db-mysql:3306/carsharepro?serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=root
    depends_on:
      - db-mysql
      - eureka-server  
      - nexus
  microservice-vehicule:
    build:
      context: ./microservice-vehicule
    ports:
      - "9085:9085"
    restart: on-failure
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:9091/eureka/
      - keycloak-client.server-url=http://172.28.93.16:18080/auth 
    depends_on:
      - eureka-server  
      - nexus
  microservice-auth:
    build:
      context: ./microservice-auth
    ports:
      - 9086:9086
    container_name: microservice-auth
    image: node-app-image
    restart: on-failure
    environment:
      - MONGO_URI=mongodb+srv://inesmsallem:30101999@cluster0.friepyw.mongodb.net/
      - EUREKA_DEFAULTZONE=eureka-server
      - EUREKA_PORT=9091
      - HOSTNAME=microservice-auth
      - PORT=9086
      - KEYCLOAK_SERVER_URL=http://172.28.93.16:18080/auth 
    depends_on:
      - mongodb
      - eureka-server
  microservice-assurance:
    build:
      context: ./microservice-assurance
    ports:
      - "9087:9087"
    restart: on-failure
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:9091/eureka/
      - keycloak-client.server-url=http://172.28.93.16:18080/auth
    depends_on:
      - eureka-server
      - nexus
  db-mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: carsharepro
      MYSQL_ROOT_PASSWORD: root
    ports:
     - "3306:3306"     
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: on-failure
  # front:
  #   build:
  #     context: ./frontend
  #   image: my-front-app
  #   ports:
  #     - "3000:3000"
  #   restart: on-failure
  #   environment:
  #     - eureka.client.serviceUrl.defaultZone=http://eureka-server:9091/eureka/
  #     - keycloak-client.server-url=http://172.28.93.16:18080/auth 
  #   depends_on:
  #     - microservice-auth
  
volumes:
    postgres_data:
      name: keycloak_postgres_data
      driver: local