version: '3.4'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: on-failure
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "1010:1010"
    restart: on-failure
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - keycloak-client.server-url=http://172.30.240.1:18080/auth # use host name or ip of the host machine
    depends_on:
      - eureka-server
  eureka-server:
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"
    restart: on-failure
  reservation-service:
    build: ./backend-ines
    ports:
      - 8088:8088
    image: reservation-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - keycloak-client.server-url=http://172.30.240.1:18080/auth 
    depends_on:
      - eureka-server

  vehicules-service:
    build: ./backend-tlili
    ports:
      - 9191:9191
    image: vehicules-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - keycloak-client.server-url=http://172.30.240.1:18080/auth 
    depends_on:
      - eureka-server  

  review-service:
    build: ./backend-belghith
    ports:
      - 8484:8484
    image: review-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - keycloak-client.server-url=http://172.30.240.1:18080/auth
      - spring.datasource.url=jdbc:mysql://db-mysql:3306/carsharepro?serverTimezone=UTC
      - spring.datasource.username=spring
      - spring.datasource.password=spring

    depends_on:
      - db-mysql
      - eureka-server  
  db-mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: carsharepro         
      MYSQL_ROOT_PASSWORD: root
    ports:
     - "3306:3306"     
  node-app:
    build:
      context: ./user-auth
    ports:
      - 3030:3030
    image: node-app-image
    restart: on-failure
    environment:
      - MONGO_URI=mongodb+srv://inesmsallem:30101999@cluster0.friepyw.mongodb.net/
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - keycloak-client.server-url=http://172.30.240.1:18080/auth 
    depends_on:
      - mongodb
  front:
    build:
      context: ./frontend
    image: my-front-app
    ports:
      - "3000:3000"
    restart: on-failure
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - keycloak-client.server-url=http://172.30.240.1:18080/auth 
    depends_on:
      - node-app
  keycloak:
    image: jboss/keycloak:11.0.0
    volumes:
      - ./keycloak-server/realm-export.json:/tmp/keycloak/config/realm-export.json
    environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        KEYCLOAK_IMPORT: /tmp/keycloak/config/realm-export.json
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
    ports:
      - "18080:18080"
    command:
      - "-b"
      - "0.0.0.0"
      - "-Djboss.socket.binding.port-offset=10000"
    restart: on-failure
    depends_on:
      - postgres
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      ports:
        - "5432:5432"
volumes:
    postgres_data:
      name: keycloak_postgres_data
      driver: local