debug: false
server:
  port: 9097
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
keycloak-client:
  server-url: http://localhost:18080/auth
  realm:  spring-micro-main
spring:
  application:
    name: microservice-assurance
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: spring-micro-producer
            client-secret: 4362afba-b98d-499d-94fd-1f0766b0c9bb
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9083/login/oauth2/code/keycloak
            scope: openid
        provider:
          keycloak:
            authorization-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/auth
            token-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/token
            user-info-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
            user-name-attribute: name
            user-info-authentication-method: header
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
  h2:
  console:
    enabled: true
    path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: ms_candidat
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

